services:
    app.shop_controller:
      class: AppBundle\Controller\ShopController
      arguments:
        - '@kfina.bewamo.shop.service'
        - '@serializer'

    kfina.bewamo.shop.service:
      class: Kfina\Bewamo\Shop\Service\ShopService
      arguments:
        - '@kfina.bewamo.shop.repository'

    kfina.bewamo.shop.repository:
      class: Kfina\Bewamo\Shop\Repository\DoctrineRepository
      arguments:
        - '@doctrine.orm.entity_manager'
        - '@kfina.bewamo.shop.doctrine.orm.mapping.classmetadata'

    kfina.bewamo.shop.doctrine.orm.mapping.classmetadata:
      class: Doctrine\ORM\Mapping\ClassMetadata
      arguments:
        - 'Kfina\Bewamo\Shop\Entity\Shop'