---

mysql_root_password: 'root-pwd'
mysql_databases:
  - name: bewamo
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: bewamo
    host: "%"
    password: 'bewamo'
    priv: "bewamo.*:ALL"